### ISSUE TITLE
[calc_disp_dat_c] progressive status

### ISSUE THREAD

**Issue by mlp6** [mlp6/fem#26]
Generating the `disp.dat` file from `nodout` can take a while, and it would be nice to see progressive output status to know how many timesteps have been completed.

**Comment by mlp6** [comment]
> do you want that output always, or as a command line option?

A command line flag like `--status` would be great.
 
> do you want it output every N timesteps, or every N seconds clock time?

After `N` timesteps would be fine.

**Comment by ndanieley** [comment]
should N be fixed, or would '--status N' be better?

**Comment by mlp6** [comment]
`--status N` would be great!

**Comment by ndanieley** [comment]
the current option flags are all single chars, like "-i input file". do you want them switched to the "--input" style, or go with "-s N"?

**Comment by ndanieley** [comment]
oh, I just realized that if you use the debug option "-d 1" the code prints each time step as it's processed. is that good enough?

**Comment by mlp6** [comment]
oh - that would be fine (didn't realize it did that)
