### ISSUE TITLE
create_pointloads_vtk.py: numNodes not returned correctly

### ISSUE THREAD

**Issue by mlp6** [mlp6/fem#65]
```UnboundLocalError: local variable 'numNodes' referenced before assignment```

**Comment by mlp6** [comment]
fails with and without specifying an element definition file

**Comment by mlp6** [comment]
Specific case failing: ```/radforce/fem/arfi_swei/E5_1kPa_sph1cm_1.00mm```

Using ```/radforce/fem/arfi_swei/mesh/nodes.dyn``` and ```/radforce/fem/arfi_swei/field/loads.dyn```.

**Comment by Ningrui-Li** [comment]
Hi Dr. Palmeri,

Usually the node files generated with `GenMesh.py` had the arguments used to generate the mesh written in the header. I usually got the number of elements and nodes info from this header, but I realize now that some of the older nodes.dyn files don't have this info available in the header. I couldn't think of a elegant way to get this info without looping through the entire elements and nodes file once, so in the meantime, I added an input argument (--numElem) where you can input the number of elements in each dimension.

I tried it now with:
`python create_pointloads_vtk.py --nodefile /radforce/fem/arfi_swei/mesh/nodes.dyn --loadfile /radforce/fem/arfi_swei/field/loads.dyn --numElem 40 160 280`
and it worked! I will try to think of a better way of doing this sometime later this week.

**Comment by mlp6** [comment]
This is a great solution... no need to make it work for all of the legacy files!
