### ISSUE TITLE
fieldC: field2dyna compilation

### ISSUE THREAD

**Issue by mlp6** [mlp6/fem#70]
```
formatExpImpResp.c:5:28: fatal error: gsl/gsl_interp.h: No such file or directory
 #include <gsl/gsl_interp.h>
```

This error was on `durmstrang`.

**Comment by ndanieley** [comment]
yeah, the c code requires the gnu scientific library, which provides the linear interpolation code. not sure how to handle that requirement.

**Comment by mlp6** [comment]
What are the packages that need to be installed for
1. CentOS
2. Fedora
3. Ubuntu
We can add that to the `README` for build instructions, or maybe make a `cmake` configuration file.

**Comment by ndanieley** [comment]
for centos and fedora, install gsl and gsl-devel. for ubuntu 18, install libgsl23 and libgsl-dev. unfortunately, that number '23' will depend on the version of ubuntu...

**Comment by mlp6** [comment]
This issue hasn't reared its head recently, so going to close this.
