### ISSUE TITLE
field2dyna and dynaField requires Field_II_Pro

### ISSUE THREAD

**Issue by AnnaEKnight** [mlp6/fem#71]
been a while since i wrote a git issue so apologies if this isn't the correct formatting
1) even though there is a nargin catch in field2dyna it still errors if it does not have the correct number of inputs (there are catches for nargin 7,8, and 11 but 9 and 10 are missing). I think i can fix this by changing the nargin catch for threads to 8 not 7, and for lownslow to 9 not 8. (assuming those without pro will not be running multithreaded or messing with lownslow.
2) in dynaField two lines cause matlab to crash if you do not have field_ii_pro (which students in my class do not):
set_field('threads', threads);
disp(sprintf('PARALLEL THREADS: %d', threads));
If you comment these out it runs fine. but non-pro field doesn't have set_field i think

let me know if you want me to submit my version with these changes? n

**Comment by mlp6** [comment]
Please do submit a Pull Request!  I will use that as a starting point to more gracefully handle this stuff.  Thanks!
