### ISSUE TITLE
probes.m files need focus_m

### ISSUE THREAD

**Issue by jameslong12** [mlp6/fem#74]
https://github.com/mlp6/fem/blob/390797fd4f1b4b877312c04d9f1ab081c9ed124c/field/field2dyna.m#L51

Some files (vf105) in the `ultrasound/probes` repository use `FIELD_PARAMS.focus_m` instead of `FIELD_PARAMS.focus`. Change one to be in concordance with the other?

**Comment by mlp6** [comment]
Ah, that is unfortunate.  We're in the middle of transitioning to using a JSON-based probe definition with C-based code that Ned D. wrote to run on the cluster much more efficiently, and this must have gotten partially deployed in the `probes` repo prematurely.  Will fix this up ASAP.

**Comment by mlp6** [comment]
fixed with commit 0c27cc05af2433bcf2fda53c6430c4423a68d04a
