### ISSUE TITLE
jsondecode broken in Matlab 2020a?

### ISSUE THREAD

**Issue by AnnaEKnight** [mlp6/fem#91]
I cannot get jsondecode to work even on the default file "field_params.json" provided in fem/fem/field.
jsondecode throws an error "JSON text must be a character vector or a scalar non-missing string."

Based on this https://www.mathworks.com/matlabcentral/answers/472574-breaking-changes-to-jsondecode-between-2018a-and-2018b
the json is reading as a nx1 when it needs to be a 1xn, so just need a single ' on line 15 of read_json.m to instead be jsonstruct = jsondecode(rawtext') to fix it. 
(this is wildly poorly documented by matlab)
I think I can make this small change myself but i dont remember what current fem repo protocol is re submitting changes? do i try to merge a pull request??

**Comment by mlp6** [comment]
Happy to accept a Pull Request!  Details on contributing here: https://github.com/mlp6/fem/blob/main/CONTRIBUTING.md

**Comment by mlp6** [comment]
@aknightmare since this is a matlab-based break, and I don't have a framework for running matlab-based unit tests in the package, you can forgo the unit test part of the Pull Request.

**Comment by AnnaEKnight** [comment]
i'm finding a few other minor issues related to the changeover to use the json framework for both the probe parameters and the field params again, the defaults do not run as they stand right now.  do i run these as separate pull requests?

**Comment by mlp6** [comment]
The JSON functionality was never formally integrated, though it is completely the direction we want to go, so any and all efforts to polish this up are **_very_** welcome!!

**Comment by AnnaEKnight** [comment]
this will be resolved by pull request #92
