### ISSUE TITLE
expand ability to extract an image plane beyond the assumed axial-lateral view

### ISSUE THREAD

**Issue by mlp6** [mlp6/fem#96]
https://github.com/mlp6/fem/blob/2aeaed5420c556381ae6e427e74b29986119b55c/fem/post/create_res_sim.py#L190 only allows you to specify an elevation location (as a float) to extract the corresponding plane; now that we're working with 3D spatial data a lot more, it would be more useful for this allow plane extraction with references defined in the other dimensions.

There is a unit test for this function (https://github.com/mlp6/fem/blob/2aeaed5420c556381ae6e427e74b29986119b55c/tests/test_create_res_sim.py#L16) that will need to remain stable for backwards compatibility with lots of existing post-processing scripts.

**Comment by AnnaEKnight** [comment]
closed with pull request [98]
