### ISSUE TITLE
need to update the example file?

### ISSUE THREAD

**Issue by AnnaEKnight** [mlp6/fem#97]
So i wrote the new version of create_res_sim which is called inside extract3Darfi which is called in test_savepvd
given that the test under the hood in test_savepvd is a straight file comparison of the example file vs the test generated file, my new version is failing because i have updated it such that under any plane saved, it also saves a single variable for the non iterated on parameter. (example if elevation = 0 is the plane pulled out) then what goes into res_sim and later the pvd is axial = -3 to 0, lateral is -1.5 to 0, and elev = 0, while previously only axial and lateral were saved). I feel this is more robust, but it does break this one point of backwards compatibility -- but i suspect this will only pop up this once because it's in the test suite?

So my questions are 1) am i reading my failed test files correctly here https://github.com/mlp6/fem/actions/runs/691858129 that this is my only issue?
and 2) do i have the authority to update said file?

**Comment by mlp6** [comment]
@AnnaEKnight can you put the requested changes to the tests in place that would get your new syntax to work and then submit a PR when all is ready, and then I can more clearly see how the API will change.

**Comment by AnnaEKnight** [comment]
okay i was incorrect - the example file does not need to be replaced. However i am not sure how to write more tests for the new dimension directions of create_res_sim.py because i'm not sure I understand how the current test cases are generated enough to write more tests? (what ends up calling test_create_res_sim/ the rest of conftest.py)

**Comment by AnnaEKnight** [comment]
closed with pull request 98
