### ISSUE TITLE
Updating example files to point at singularity and have wrapper scripts?

### ISSUE THREAD

**Issue by AnnaEKnight** [mlp6/fem#99]
can i update at least the two example folders under compress_cube and gauss_qsym_pml to 1) point at the singularity container created by OIT and 2) have bash wrapper scripts that call them or is that workflow not stable enough as how we are moving forward yet? 
obviously would do as a pull request etc.

**Comment by mlp6** [comment]
The singularity container approach is now deprecated in favor of a module load approach.  The cluster launching scripts are, in general, tricky to generalize for users outside Duke's DCC environment.
